package obtuseloot.evolution;

public enum MechanicNicheTag {
    NAVIGATION,
    STRUCTURE_SENSING,
    ENVIRONMENTAL_SENSING,
    MEMORY_HISTORY,
    FARMING_WORLDKEEPING,
    RITUAL_STRANGE_UTILITY,
    SOCIAL_WORLD_INTERACTION,
    INSPECT_INFORMATION,
    MOBILITY_UTILITY,
    PROTECTION_WARDING,
    ENVIRONMENTAL_ADAPTATION,
    SUPPORT_COHESION,
    RARE_HIGH_COST_UTILITY,
    GENERALIST
}
