package obtuseloot.lineage;

public enum LineageBiasDimension {
    ACTIVE_BEHAVIOR,
    MEMORY_REACTIVITY,
    SPECIALIZATION,
    COMPETITION_TOLERANCE,
    WEIRDNESS,
    RARITY_APPETITE,
    RISK_APPETITE,
    PATIENCE,
    BUDGET_DISCIPLINE,
    EXPLORATION_PREFERENCE,
    SUPPORT_PREFERENCE,
    RITUAL_PREFERENCE,
    ENVIRONMENTAL_SENSITIVITY,
    UTILITY_DENSITY_PREFERENCE,
    RELIABILITY
}
