package com.gemini.obtuseloot.lore;

import java.util.Arrays;
import java.util.List;

/**
 * Default lore entries for observations — curated entries.
 * Server owners can replace the generated .yml file freely; this class
 * is only used when the file does not yet exist.
 *
 * Register: Sentence case. Present-tense physical description of the item.
 * This is the FIRST segment of the lore line:
 *   [Observation] — [History] — [Secret].
 */
final class Observations {
    private Observations() {}

    static List<String> get() {
        return Arrays.asList(

        // ── Physical condition ────────────────────────────────────────────────
        "Still warm to the touch", "Scorched at the edges", "It never rusts",
        "Colder than the air around it", "Hums faintly in darkness",
        "The handle has been rewrapped many times",
        "Heavier than it looks", "Lighter than it should be",
        "Reflects no light", "Casts a shadow even indoors",
        "The material is unfamiliar", "Smells faintly of smoke",
        "Smells of old rain", "Leaves no fingerprints",
        "It is impossibly sharp", "Notched from heavy use",
        "Polished to a mirror finish",
        "The base is worn smooth from years of contact",
        "Etched with a name no one recognizes",
        "Bears a crest long since forgotten",
        "The weight shifts when held", "Resonates at a low frequency",
        "The material is darker than it should be",
        "Flecked with embers that never cool",
        "Traced with veins of pale light",
        "Bound in leather from an unknown beast",
        "The frame is bent inward where it should be straight",
        "Wrapped in fraying silk", "Smells of iron and old earth",
        "The base glows faintly at dusk",
        "No maker's mark can be found",
        "The runes shift when not observed",
        "Warm as a living thing", "Ice-cold at the core",
        "Hisses faintly in rain", "Vibrates when danger is near",
        "Dims surrounding light", "Brightens in darkness",
        "It has never been stored away properly",
        "Cracked but never broken", "It weeps when heated",
        "Leaves frost where it rests",
        "Draws the eye from across a room",
        "Repels flies and insects",
        "The grain of the material runs in the wrong direction",
        "Feels like it has been used today",
        "Feels like it has not moved in centuries",
        "Blood does not stick to it",
        "Any damage repairs itself overnight",
        "The handle bears old sweat stains",
        "Set with a gem of unknown origin",
        "The gem pulses once per hour",
        "Worn smooth on one side only", "The balance is perfect",
        "Slightly too large for any known hand",
        "Slightly too small to be practical",
        "It rings when struck but never chips",
        "Sounds hollow when tapped",
        "The working surface curves imperceptibly",
        "Radiates a faint warmth in winter",
        "Radiates a faint chill in summer",
        "Attracts dust but never dirt",
        "Tarnishes in moonlight", "Gleams in moonlight",
        "The shadows around it move incorrectly",
        "Leaves no mark when set down",
        "Leaves a scorched outline on every surface",
        "The wrapping never frays regardless of use",
        "The stitching is coming undone",
        "Inscribed on the inside where no tool could reach",
        "The inscription changes depending on the reader",
        "Bears the marks of three different smiths",
        "Was clearly made for someone else",
        "Fits the hand like it was always yours",
        "Pulls slightly to the left",
        "Always points north when balanced on a finger",
        "Smells of a hearth that has long gone cold",
        "Smells of a fire that is still burning somewhere",
        "It is warm on one side and cold on the other",
        "It has been remade at least once",
        "It has never needed maintenance of any kind",
        "The surface is covered in fine scratches",
        "The surface is completely unmarked",
        "The base unscrews but the chamber inside is empty",
        "The base piece cannot be removed by any means tried",
        "Heavier at the far end than the near end",
        "Heavier at the near end than the far end",
        "One side is heavier than the other by design",
        "Bears a lock that has no key", "The lock is already open",
        "Wrapped in a material that absorbs sound",
        "Makes no sound when drawn", "Rings loudly when drawn",
        "Faintly luminescent in total darkness",
        "Becomes invisible in bright light",
        "Casts a double shadow", "Casts no shadow at all",
        "Feels wet though it is dry", "Feels dry though it is wet",
        "The surface is striped with faint and persistent color",
        "Seems to breathe when held",
        "The handle tightens when gripped firmly",
        "The handle loosens when danger is near",
        "Smells of pine resin", "Smells of the sea",
        "Smells of turned earth", "Smells of lightning",
        "Smells of nothing at all", "Heats up in anger",
        "Cools in calm", "Responds to heartbeat",
        "Grows heavier as the day passes",
        "Grows lighter toward midnight",
        "The color deepens in blood", "The color fades in sunlight",
        "The markings are in an extinct script",
        "The markings spell nothing legible",
        "The markings are a map of nowhere known",
        "Bears a thumbprint burned into its surface",
        "The thumbprint is not human",
        "Wrapped in chains that serve no purpose",
        "The chain links are too small to have been made by hand",
        "The handle has been burned once and not replaced",
        "It has been bent and straightened at least once",
        "Keeps its sharpness regardless of use",
        "Shows wear by evening and recovers fully by morning",
        "A channel running its length is carved with faces",
        "The faces along the channel change each time you look",
        "Bears the glyph of a dead god",
        "Bears the glyph of a living one",
        "The material is liquid at its very center",
        "It is hollow but stronger for it",
        "Heavier in silence", "Lighter when music plays",
        "A portrait is engraved on it of someone familiar",
        "The portrait is always looking at you",
        "The portrait is always looking away",
        "Stained a deep and permanent crimson",
        "Stained a pale and permanent white",
        "One end is blunted but the rest remains in perfect condition",
        "The main surface shows wear but the far end is pristine",
        "Found with a note that has since dissolved",
        "Accompanied by a key that fits nothing",
        "The leather grip smells of rain on stone",
        "Trembles faintly when pointed east",
        "Trembles faintly when pointed at the sky",
        "The balance shifts with the seasons",
        "Seven notches are cut into it at uneven intervals",
        "The number of notches changes each morning",
        "It rings at a specific note when struck",
        "The note has no name in any scale",
        "Covered in a fine and immovable patina",
        "Bright as the day it was forged",
        "The forging date is stamped but illegible",
        "The forging date is a date in the future",
        "Pulls toward underground water", "Pulls toward fire",
        "Repels water", "Repels flame",
        "Neither rusts nor corrodes",
        "Corrodes only in moonlight",
        "Corrodes only in direct sunlight",
        "It is thinner at the center than at its edges",
        "Bears a language spoken in dreams",
        "Bears no language at all",
        "Glows briefly when a lie is told nearby",
        "Dims briefly when a vow is made nearby",
        "The handle is cold when the body is warm",
        "The handle is warm when the body is cold",
        "Wrapped in the hide of something enormous",
        "Chimes when moved through fog",
        "Whistles when moved through rain",
        "Silent in every condition",
        "Found buried face-down", "Found buried point-up",
        "Found floating", "Found sealed in stone",
        "Found in fire and undamaged",
        "Bears old blood that does not wash off",
        "Bears no blood despite its history",
        "Engraved with a number that counts down",
        "Engraved with a number that is nearly at zero",
        "Engraved with a number that counts up",
        "It shifts color with temperature",
        "Bright blue in cold and deep red in heat",
        "Cool to the touch in all climates",
        "Warm to the touch in all climates",
        "It whistles at a specific wind speed",
        "It is silent at all wind speeds",
        "Heavier when moving toward something",
        "Lighter when moving away",
        "Bears the wear of centuries",
        "Bears no wear despite centuries of use",
        "Still has the maker's polish on one face",
        "The polish is on the wrong side",
        "A faint heartbeat can be felt through the handle",
        "Two heartbeats can be felt through the handle",
        "The heartbeat felt through the handle belongs to no one present",
        "It bends light very slightly near its surface",
        "It absorbs light entirely in certain conditions",
        "It radiates enough warmth to be perceived in darkness",
        "Casts heat shimmer in cold air",
        "Frost forms on it in warm rooms",
        "No fingerprints will stay on the surface",
        "Only one fingerprint remains and it is ancient",
        "The guard is engraved inside where nothing could reach",
        "Bears evidence of a repair made from within",
        "Found wrapped in a shroud",
        "Found inside a locked chest with no key",
        "Found inside a chest that contains nothing else",
        "The original owner's name is scratched out",
        "Three names are scratched out",
        "A new name has been added recently",
        "The handle is made of bone",
        "The bone is not from any known animal",
        "A sealed chamber near the base contains a small amount of liquid",
        "The liquid does not evaporate",
        "The liquid is different colors at different times",
        "Still faintly smells of its last use",
        "Smells of a place you have never been",
        "Smells of home, whatever that means to you",
        "Feels familiar though you have never held it",
        "Feels wrong though you have held it before",
        "The weight is distributed perfectly for your height",
        "The weight is distributed perfectly for someone taller",
        "The material is layered like wood grain",
        "The layers shift when held at different angles",
        "Inlaid with a material that predates any known craft",
        "Its sharpest part cannot be covered by a shadow",
        "Its point always seems lit regardless of conditions",
        "The handle was made to suit many different hands",
        "The handle was made for one specific hand",
        "Engraved with a quote in no known tongue",
        "The quote is different each morning",
        "It has been worked to its final form",
        "Cannot be refined further without risk of breaking",
        "Restores itself on moonless nights",
        "Dulls itself on nights when the moon is full",
        "Unscrewing the base reveals a small hollow chamber",
        "The chamber smells of old herbs",
        "The herbs are still faintly fragrant",
        "Balanced to work with one hand only",
        "Balanced equally for either hand",
        "It tilts slightly toward magnetic north when balanced",
        "The runes on it spell a name written in reverse",
        "The name backwards is unpronounceable",
        "Set with a gem that changes color in heat",
        "Set with a gem that is always the same temperature",
        "The gem fell out once and reappeared",
        "The gem has never been removed",
        "The gem appears to have grown into the material",
        "Faintly magnetized", "Repels iron shavings",
        "Attracts iron shavings",
        "The balance point shifts overnight",
        "The balance point has never changed",
        "A date is stamped into it where it will not easily be seen",
        "The date predates any known civilization",
        "The date is tomorrow", "The date changes each morning",
        "Has been submerged in water and remained dry",
        "Has been held in fire and remained cool",
        "Bears heat damage from something far hotter than flame",
        "Bears cold damage from something far colder than ice",
        "The handle is worn differently on each side",
        "The handle is not worn at all",
        "Found with no case and no covering of any kind",
        "Found with a case that fits nothing else",
        "The case is newer than the item it holds by centuries",
        "The case is older than the item it holds",
        "Makes a sound like distant thunder when drawn fast",
        "Makes a sound like distant rain when drawn slowly",
        "A symbol on it appears different in every mirror",
        "No marking on it appears in any mirror",
        "The surface temperature is exactly body heat",
        "Attracts birds", "Repels birds", "Repels animals generally",
        "Animals are drawn to it", "Cats will not approach it",
        "Small flowers grow near it when left in soil",
        "Soil turns dark around it", "Soil turns pale around it",
        "Mushrooms grow near it in darkness",
        "Nothing grows near it", "The surrounding air is always still",
        "It oxidizes in a pattern rather than uniformly",
        "The oxidation pattern resembles a map",
        "The map shows a location that does not exist",
        "The map shows your exact current location",
        "The oxidation pattern resembles a face",
        "The face in the oxidation is screaming",
        "The face in the oxidation is smiling",
        "The face changes expression when you look away",
        "There is no face if you look directly",
        "The material has a grain like wood",
        "The grain runs in impossible directions",
        "Heats quickly but cools slowly",
        "Heats slowly but cools immediately",
        "Does not conduct heat in one direction",
        "It leaves no residue when worked",
        "Its surface cannot be polished further",
        "Something shifts audibly inside with a steady rhythm",
        "The internal rhythm follows a pattern that repeats exactly",
        "The internal rhythm matches the tidal pull of a distant sea",
        "It is thinner at its narrowest than any known process should allow",
        "Light passes through the thinnest point in certain conditions",
        "Light bends slightly around the flat",
        "The base end is heavier than the rest of it combined",
        "Its color varies noticeably in shadow",
        "It appears to be two different materials at once",
        "Vibrates at a frequency that makes teeth ache",
        "Vibrates at a frequency that calms breathing",
        "The vibration stops when touched",
        "The vibration increases when touched",
        "Resonates with the sound of a voice long gone",
        "Resonates with wind passing through valleys",
        "Resonates with the sound of deep water",
        "Resonates only with silence",
        "The handle changes texture depending on the holder's state",
        "The handle becomes rough when danger is near",
        "The handle becomes smooth in safety",
        "Found at the bottom of a well",
        "Found at the top of an unmarked grave",
        "Found in the hand of a statue",
        "Found with no explanation and no witness",
        "A letter was found with it but addressed to no one",
        "A letter was found with it but written in blood",
        "A letter was found with it and made no sense",
        "A letter told you to give it away",
        "A letter told you to never let it go",
        "It was already named when found",
        "The name on it was wrong for the item",
        "The name on it was exactly right",
        "The name on it was yours",
        "It has outlasted its own name",
        "The name has outlasted everything else",
        "There is no name anywhere on it",
        "The name appears only in direct flame",
        "The name disappears when written down",
        "The name sounds different each time it is spoken",
        "It has three names and no one agrees which is true",
        "The weight has been slowly increasing for years",
        "The weight has been slowly decreasing",
        "The weight changes on cloudy days",
        "Wrapped once in a flag that no longer exists",
        "Wrapped once in the cloak of someone famous",
        "The handle absorbs sound passing through it",
        "The handle amplifies sound passing through it",
        "The handle conducts distant sound into the hand",
        "It is warm in the early morning",
        "It is cold at midday",
        "It is neither warm nor cold at midnight",
        "The balance tilts toward the hand that holds it",
        "Etched with constellations that do not appear in any sky",
        "Etched with a constellation that no longer exists",
        "Glows briefly when submerged in water",
        "Goes dark when submerged in water",
        "Floats despite its density",
        "Sinks despite being lighter than water",
        "It is the same width from handle to tip",
        "There is one intentional flaw and it is on the inside",
        "The intentional flaw is in the shape of a letter",
        "The letter in the flaw changes to match whoever holds it",
        "Humming at the very threshold of hearing",
        "Silent unless the world is silent first",
        "Loud in silence and quiet in noise",
        "The hum rises at dawn", "The hum falls at dusk",
        "The hum is a song that cannot be named",
        "The hum is a name that cannot be sung",
        "Cold in summer and warm in winter",
        "The body is older than the handle by a thousand years",
        "The handle is older than the body",
        "The repairs are indistinguishable from the original",
        "The repairs are obvious but stronger",
        "Smells of a forge that burned down long ago",
        "Smells of a city that no longer exists",
        "Smells of something that has not happened yet",
        "The smell changes based on who is holding it",
        "Heavier than memory suggests",
        "Lighter than expected after all these years",
        "The wear patterns suggest a left-handed previous owner",
        "The wear patterns suggest someone much taller",
        "The wear patterns suggest multiple owners of the same size",
        "The wear patterns suggest it was never used in combat",
        "The wear patterns suggest it was used constantly",
        "The wear patterns suggest someone grieving",
        "There is a notch that was put there on purpose",
        "The notch counts something",
        "The notch fits a claw perfectly",
        "The grain of the material tells a story",
        "The story in the grain does not have an ending",
        "The story in the grain has ended but it persists",
        "The grain moved this morning",
        "The grain moves when no one is watching",
        "It hums at the same pitch as the wind before a storm",
        "The handle has been re-wrapped exactly seventeen times",
        "The seventeenth wrapping is the original material",
        "The base end is warm on the side closest to the body",
        "The base end is cold on the side facing away",
        "The balance shifts when the temperature drops",
        "It rests differently on stone than on wood",
        "It does not ring when struck against iron",
        "It rings clearly against copper and nothing else",
        "It swells slightly in humid weather",
        "It contracts in dry cold and holds tighter",
        "It is wider than any mold that could have made it",
        "It is narrower than any tool that could have finished it",
        "An outline is visible through its surface when submerged",
        "The outline beneath the surface is described differently by everyone",
        "Appears to bend slightly when viewed from a distance",
        "Bends toward different things for different holders",
        "A hollow cavity inside is engraved with a human silhouette",
        "The engraved silhouette changes posture between viewings",
        "One section is warmer than the rest by two degrees exactly",
        "Something moves inside the frame with no repeating rhythm",
        "There are stress marks that were not there last year",
        "The stress marks resolve into letters at certain angles",
        "The letters are not in any language",
        "The letters change month to month",
        "Both ends are worn to exactly the same degree",
        "The dulling is deliberate and recent relative to its age",
        "It leans imperceptibly toward whoever is speaking",
        "It leans away when voices are raised",
        "It stands upright on its base with no assistance",
        "It has never fallen over when placed this way",
        "The base is perfectly flat despite every visible reason it should not be",
        "Something about it makes animals calm",
        "Something about it makes animals still and watchful",
        "It conducts sound from the ground through the handle",
        "The sound changes below a certain depth and then stops entirely",
        "It carries a charge that dissipates slowly over hours",
        "The charge returns by morning with no visible cause",
        "The charge is not electrical in any measurable sense",
        "The charge affects the mood of whoever holds it consistently",
        "The mood it produces has no agreed name",
        "The closest description is quiet certainty",
        "It is always found facing the same direction when left alone",
        "The direction changes by season",
        "In winter it faces exactly toward the nearest fire",
        "In summer it faces toward open water",
        "During storms it faces straight up",
        "The scratches on the flat are in groups of three at uneven intervals",
        "The spacing between scratch-groups encodes something when measured precisely",
        "The surface changes how much light it reflects between viewings",
        "Reflects more light than the source provides",
        "Its reflectivity varies with no measurable cause",
        "A mark on the inside of the guard was not made with metal",
        "The mark inside the guard resembles a thumbprint from something large",
        "The smell changes over the course of a day",
        "Morning: earth. Noon: nothing. Dusk: smoke. Night: rain.",
        "The cycle is consistent regardless of location or weather",
        "A vibration starts at moonrise and ends at moonset",
        "The vibration at moonrise is only perceptible to certain people",
        "Bees do not land on it",
        "Bees fly in a deliberate pattern around it",
        "The material has three distinct layers visible at its thinnest point",
        "The innermost layer is the hardest and the outermost the softest",
        "The middle layer does not behave like metal under testing",
        "The testing of the middle layer was documented once and then halted",
        "Fire behaves differently around it",
        "Flames lean away from it rather than toward rising heat",
        "There is no theory that explains all of its behaviors together",
        "Extended holding produces minor perceptual changes in some people",
        "Setting it down produces a brief sense of loss in those affected",
        "It has been weighed many times and the weight is never the same",
        "The weight variation matches tree-ring width records from nearby",
        "The engraving predates the event it depicts",
        "It does not reflect light the same way from the left as the right",
        "Photographs of it take longer to develop than others",
        "The developed images show detail not present at time of capture",
        "It has been left in a room alone and found across the room",
        "The marks at the threshold began and ended there and nowhere else",
        "Light passes through its thinnest point at a certain angle of afternoon sun",
        "The light that passes through arrives a different color on the other side",
        "It feels different to the same person on different days",
        "The sub-sensory difference affects grip confidence over time",

        // ── Earns a second reading in lore context ────────────────────────────
        // All are genuine physical descriptions of an artifact; the second reading
        // emerges only when combined with the right item name, history, and secret.
        "Grows warm with extended use",
        "Yields slightly under sustained pressure",
        "Responsive to the warmth of a hand",
        "The inside is warmer than the outside",
        "The grip leaves a residue of warmth on the hand",
        "Softer to the touch than it appears",
        "Slick when warm and rougher when cold",
        "Narrower at the middle than at either end",
        "Wider at the base than at the tip",
        "The hollow near the base accommodates a single finger precisely",
        "Holds heat long after the source of warmth has gone",
        "Easier to hold the longer it is held",
        "Responds noticeably to sustained contact",
        "The texture smooths with the heat of the hand",
        "The surface is smooth in one direction only",
        "The handle yields slightly under a firm and sustained grip",
        "Quivers faintly when first picked up",
        "The quivering subsides once the holder is calm",
        "Longer when laid flat than it appears in hand",
        "The material gives slightly and springs back",
        "It fits differently depending on the approach",
        "Tightens perceptibly as the grip tightens",
        "Goes pleasantly slack when not in active use",
        "The hollow in the frame deepens with use",
        "Holds its warmth through the night",
        "Leaves an impression of itself on whatever surface it rests against",
        "Vibrates noticeably when held in a closed hand",
        "The tip is polished smoother than the rest",
        "Worn primarily at the grip end",
        "Swells perceptibly in warm conditions",
        "Contracts noticeably in cold",
        "Produces a low hum under sustained use",
        "The shaft is longer than it appears when not in use",
        "Fills the hand more completely the longer it is held",
        "The tip leaves a faint impression on whatever it touches",
        "The base is warmer than the tip by several degrees",
        "Softer toward one end than the other",
        "Moister to the touch than expected",
        "Goes rigid when held firmly for an extended period",
        "Relaxes completely when set down",
        "Tapers elegantly from base to tip",
        "The inside is considerably larger than the outside suggests",
        "Produces a sound under rapid movement that cannot be called mechanical",
        "Noticeably more pliable than it appears",
        "Most responsive when approached slowly"
    );
    }
}
