package obtuseloot.abilities;

public enum AbilityTrigger {
    ON_HIT,
    ON_KILL,
    ON_MULTI_KILL,
    ON_BOSS_KILL,
    ON_MOVEMENT,
    ON_LOW_HEALTH,
    ON_REPOSITION,
    ON_CHAIN_COMBAT,
    ON_DRIFT_MUTATION,
    ON_AWAKENING,
    ON_FUSION,
    ON_MEMORY_EVENT,
    ON_WORLD_SCAN,
    ON_STRUCTURE_SENSE,
    ON_BLOCK_HARVEST,
    ON_ENTITY_INSPECT,
    ON_BLOCK_INSPECT,
    ON_RITUAL_INTERACT,
    ON_SOCIAL_INTERACT,
    ON_WITNESS_EVENT
}
