package obtuseloot.abilities;

public enum AbilityEffectType {
    COMBAT_INTERACTION,
    TRIGGERED_BEHAVIOR,
    ENEMY_INTERACTION,
    TEMPORARY_STATE,
    BATTLEFIELD_INFLUENCE,
    CONDITIONAL_MECHANIC,
    MOVEMENT_INTERACTION,
    TIMING_MECHANIC,
    FLAT_STAT
}
