package obtuseloot.abilities;

public enum TriggerSuppressionReason {
    HOLDER_BUDGET_EXHAUSTED,
    ARTIFACT_BUDGET_EXHAUSTED,
    TRIGGER_TYPE_BUDGET_EXHAUSTED,
    ABILITY_BUDGET_EXHAUSTED,
    BURST_CAP_EXCEEDED,
    ANTI_SPAM_SUPPRESSION,
    REPEATED_NO_OP_SUPPRESSION,
    POLICY_DENIED,
    UNKNOWN
}
